### ISSUE TITLE
Mssing `prebuild.bat` file

### ISSUE THREAD

**Issue by jie65535** [hms11rn/MtpJava#1]
Delete dll
  The system cannot find the specified path.
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: Command “C:\Users\hmsel\git\CPP\jmtp\cpp\x64\prebuild.bat
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: :VCEnd” Exited. Code 3.

**Comment by hms11rn** [comment]
Fixed
